config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  root 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
  validates :name, length: { minimum: 3, maximum: 20 }, presence: true
  validates :url, length: { minimum: 5 }, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :registered_applications
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_access_control_headers

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    render json: "Unregistered application", status: :unprocessable_entity and return unless registered_application
    @event = registered_application.events.build(event_params)

    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :set_registered_application, only: [:show, :delete, :destroy]

  def index
    @registered_applications = current_user.registered_applications
  end

  def show
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    @registered_application.user = current_user

    if @registered_application.save
      flash[:notice] = "Your application was saved."
      redirect_to action: "index"
    else
      @errors = @registered_application.errors
      error_log = ""
      @errors.full_messages.each do |error|
        error_log+=error
      end
      flash.now[:alert] = error_log
      render :new
    end
  end


  def delete

  end

  def destroy

    if @registered_application.destroy
      flash[:notice] = "#{@registered_application.name} was deleted."
      redirect_to action: "index"
    else
      flash.now[:alert] = "Error - this application could not be deleted."
      render :show
    end

  end

  private

  def set_registered_application
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html  { redirect_to @user, notice: "User was successfully updated" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role, :user_name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">
    <%= link_to 'Blocmetrics', root_path, :class => "navbar-brand" %>
  </div>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item"><%= link_to 'Register New Application', new_registered_application_path, :class => 'nav-link text-secondary' %></li>
    <li class="nav-item"><%= link_to 'Your Registered Applications', registered_applications_path, :class => 'nav-link text-secondary' %></li>
    <% if user_signed_in? %>
    <li class="nav-item"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %></li>
    <li class="nav-item"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link' %></li>
    <% else %>
    <li class='nav-item'><%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link' %></li>
    <li class='nav-item'>  <%= link_to "Sign In", new_user_session_path, :class => 'nav-link'  %></li>
    <% end %>
    <li class='nav-item nav-link'>  Signed in as: <strong><%= current_user.email %></strong> </li>
  </ul>
</nav>






<body>

<p class="notice"> <%= notice %> </p>
<p class="alert"> <%= alert %> </p>
<%= yield %>

</body>

</html>

app/views/registered_applications/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">App Name</th>
      <th scope="col">Url</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @registered_applications.each_with_index do |reg_app, i| %>
    <tr scope="row">
      <td> <%= i + 1 %> </td>
      <td><%= reg_app.name %></td>
      <td><%= link_to reg_app.url, reg_app %></td>
      <td><%= link_to "Edit", edit_registered_application_path(reg_app) %></td>
      <td><%= link_to "Delete", registered_application_path(reg_app), method: :delete, data: { confirm: "Are you sure you want to delete this app?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/registered_applications/new.html.erb
<h2>Register an application</h2>

<div class="row">
  <% if @registered_application.errors.any? %>
    <div class="alert alert-danger">
      <h4> <%= pluralize(@registered_application.errors.count, "error") %> </h4>
      <ul>
        <% @registered_application.errors.full_messages.each do |error_msg| %>
          <li> <%= error_msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-8">
    <%= form_for @registered_application do |f| %>
    <%= form_group_tag(@registered_application.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter your website's nickname" %>
        <% end %>
      <%= form_group_tag(@registered_application.errors[:url]) do %>
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter your website's nickname" %>
      <% end %>
        <div class="form-group">
        <%= f.submit "Create", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<div class="jumbotron text-center">
  <h2> Analytics page for "<%= @registered_application.name %>" </h2>  -
</div>
<div class="container">
  <div class="col-md-4">
    <p> URL : <%= @registered_application.url %></p>
  </div>
  <div class="col-md-4">

  <%= pie_chart @registered_application.events.group(:name).count %>
  <p>Total events over time:</p>
  <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.email %>
  <%= link_to "View Profile", user %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h2> Welcome to  <%= @user.email %>'s profile page </h2>

<h4> This user has registered these applications: </h4>
<% @user.registered_applications.all.each do |reg_app| %>
  <div> <%= link_to reg_app.url, [@user, reg_app] %> </div>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome to Blocmetrics!</h1>
  <p class="lead">Want to know what your website is doing? We can help!</p>
  <hr class="my-4">
  <p>Blocmetrics is a lightweight, customizable app that allows you to track user actions on your website.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>